[tool]
id = "ncbi-datasets-cli"
version = "16.30.0"
description = "NCBI Datasets command-line: fetch genomes, genes, and metadata"
homepage = "https://github.com/ncbi/datasets"
license = "Public Domain"
tier = "core"
maintainers = [ "github:ncbi",]
[[tool.inputs]]
name = "query"
type = "file"
cardinality = "one"
description = "Accession or taxon query"

[[tool.outputs]]
name = "package"
type = "file"
cardinality = "one"
description = "Datasets ZIP package"

[tool.image]
backend = "docker"
reference = "ghcr.io/tejasprabhune/bv-pkg/ncbi-datasets-cli:16.30.0"

[tool.hardware]
cpu_cores = 2
ram_gb = 4.0
disk_gb = 50.0

[tool.entrypoint]
command = "datasets"

[tool.binaries]
exposed = [ "datasets", "dataformat",]

[tool.factored]
spec_path = "specs/ncbi-datasets-cli/16.30.0.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/ncbi-datasets-cli:16.30.0"
image_digest = "sha256:995bc570199fdd4485733554ab89fa87d865c1b467379b218afa2fbd614d3bce"
