[tool]
id = "hyphy"
version = "2.5.62"
description = "HYPHY: hypothesis testing for molecular evolution and selection"
homepage = "https://www.hyphy.org/"
license = "MIT"
tier = "community"
maintainers = [ "github:veg",]
[[tool.inputs]]
name = "aln"
type = "msa"
cardinality = "one"
description = "Codon alignment"

[[tool.inputs]]
name = "tree"
type = "file"
cardinality = "one"
description = "Newick tree"

[[tool.outputs]]
name = "json"
type = "file"
cardinality = "one"
description = "Selection analysis results"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/hyphy:2.5.62--h0d74fca_1"

[tool.hardware]
cpu_cores = 8
ram_gb = 16.0
disk_gb = 5.0

[tool.entrypoint]
command = "hyphy"

[tool.binaries]
exposed = [ "hyphy",]

[tool.factored]
spec_path = "specs/hyphy/2.5.62.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/hyphy:2.5.62"
image_digest = "sha256:9bcd8f47b5dc15b88a9d6b45fb49146b5079b27fbd3718f6ca699d3ddcca8ba9"
