name = "pilon"
version = "1.24"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["pilon ==1.24"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/pilon"
