[tool]
id = "smina"
version = "2020.12.10"
description = "AutoDock Vina fork with custom scoring functions"
homepage = "https://sourceforge.net/projects/smina/"
license = "GPL-2.0"
tier = "community"
maintainers = ["github:mwojcikowski"]

[[tool.inputs]]
name = "receptor"
type = "file"
cardinality = "one"
description = "Receptor"

[[tool.inputs]]
name = "ligand"
type = "file"
cardinality = "one"
description = "Ligand"

[[tool.outputs]]
name = "out"
type = "file"
cardinality = "one"
description = "Docked poses"

[tool.image]
backend = "docker"
reference = "ghcr.io/tejasprabhune/bv-pkg/smina:2020.12.10"

[tool.hardware]
cpu_cores = 4
ram_gb = 8.0
disk_gb = 5.0

[tool.entrypoint]
command = "smina"

[tool.binaries]
exposed = ["smina"]

[tool.factored]
spec_path = "specs/smina/2020.12.10.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/smina:2020.12.10"
image_digest = "sha256:1a51a7c371b6f1e93f8386fe09978a3bc21311b277e8f6fd5037b063124cc07f"
