name = "hicup"
version = "0.9.2"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["hicup ==0.9.2"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/hicup"
