[tool]
id = "cnvkit"
version = "0.9.10"
description = "Copy number variant detection from targeted DNA sequencing"
homepage = "https://github.com/etal/cnvkit"
license = "Apache-2.0"
tier = "community"
maintainers = ["github:etal"]

[[tool.inputs]]
name = "bam"
type = "bam"
cardinality = "many"
description = "Tumor/normal BAMs"

[[tool.inputs]]
name = "ref"
type = "fasta"
cardinality = "one"
description = "Reference"

[[tool.outputs]]
name = "outdir"
type = "dir"
cardinality = "one"
description = "CNV results"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/cnvkit:0.9.10--pyhdfd78af_0"

[tool.hardware]
cpu_cores = 4
ram_gb = 16.0
disk_gb = 10.0

[tool.entrypoint]
command = "cnvkit.py"

[tool.binaries]
exposed = ["cnvkit.py"]

[tool.factored]
spec_path = "specs/cnvkit/0.9.10.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/cnvkit:0.9.10"
image_digest = "sha256:608a1cdc1d97c57c1e7326432e1f36bf9bf9f6d1b51513faadabd2b2a8297aac"
