name = "panaroo"
version = "1.5.1"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["panaroo ==1.5.1"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/panaroo"
