name = "maxbin2"
version = "2.2.7"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["maxbin2 ==2.2.7"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/run_MaxBin.pl"
