name = "snpsift"
version = "5.4.0"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["snpsift ==5.2"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/SnpSift"
