name = "entrez-direct"
version = "22.4"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["entrez-direct ==22.4"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/efetch"
