[tool]
id = "repeatmasker"
version = "4.1.7"
description = "Mask repetitive DNA using a curated library"
homepage = "http://www.repeatmasker.org/"
license = "OSL-2.1"
tier = "community"
maintainers = [ "github:rmhubley",]
[[tool.inputs]]
name = "genome"
type = "fasta"
cardinality = "one"
description = "Genome assembly"

[[tool.outputs]]
name = "outdir"
type = "dir"
cardinality = "one"
description = "Masked sequence + reports"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/repeatmasker:4.1.7p1--pl5321hdfd78af_1"

[tool.hardware]
cpu_cores = 16
ram_gb = 32.0
disk_gb = 50.0

[tool.entrypoint]
command = "RepeatMasker"

[tool.binaries]
exposed = [ "RepeatMasker",]

[tool.factored]
spec_path = "specs/repeatmasker/4.1.7.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/repeatmasker:4.1.7"
image_digest = "sha256:405037c9f0b4e3ed0268f77280c7d747e55b7a33ff11985116051ea4af948c2e"
