name = "pairtools"
version = "1.1.0"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["pairtools ==1.1.0"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/pairtools"
