[tool]
id = "mrbayes"
version = "3.2.7"
description = "Bayesian phylogenetic inference using MCMC"
homepage = "https://nbisweden.github.io/MrBayes/"
license = "GPL-3.0"
tier = "community"
maintainers = [ "github:NBISweden",]
[[tool.inputs]]
name = "nexus"
type = "file"
cardinality = "one"
description = "NEXUS-formatted alignment + commands"

[[tool.outputs]]
name = "out"
type = "file"
cardinality = "one"
description = "Posterior trees and parameters"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/mrbayes:3.2.7a--hcee41ef_0"

[tool.hardware]
cpu_cores = 16
ram_gb = 32.0
disk_gb = 10.0

[tool.entrypoint]
command = "mb"

[tool.binaries]
exposed = [ "mb",]

[tool.factored]
spec_path = "specs/mrbayes/3.2.7.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/mrbayes:3.2.7"
image_digest = "sha256:e8564b6d2dbafdc73a3e42a74e0d6c3a5dfe7e91afe8b977405c1a9b63f85814"
