[tool]
id = "winnowmap"
version = "2.03"
description = "Long-read mapper that downweights repetitive minimizers"
homepage = "https://github.com/marbl/Winnowmap"
license = "Public Domain"
tier = "community"
maintainers = ["github:marbl"]

[[tool.inputs]]
name = "ref"
type = "fasta"
cardinality = "one"
description = "Reference"

[[tool.inputs]]
name = "reads"
type = "fastq"
cardinality = "one"
description = "Long reads"

[[tool.outputs]]
name = "sam"
type = "sam"
cardinality = "one"
description = "Alignments"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/winnowmap:2.03--h5ca1c30_4"

[tool.hardware]
cpu_cores = 16
ram_gb = 64.0
disk_gb = 50.0

[tool.entrypoint]
command = "winnowmap"

[tool.binaries]
exposed = ["winnowmap", "meryl"]

[tool.factored]
spec_path = "specs/winnowmap/2.03.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/winnowmap:2.03"
image_digest = "sha256:4aba56bb0021ad5d0fc3db81a8f8a8180800b93449d29cbef9cdb10327a85a20"
