[tool]
id = "amrfinderplus"
version = "4.0.3"
description = "NCBI AMR gene and point mutation finder"
homepage = "https://github.com/ncbi/amr"
license = "Public Domain"
tier = "core"
maintainers = [ "github:ncbi",]
cache_paths = [ "/cache/amrfinder",]
[[tool.inputs]]
name = "fasta"
type = "fasta"
cardinality = "one"
description = "Nucleotide or protein FASTA"

[[tool.outputs]]
name = "tab"
type = "tabular"
cardinality = "one"
description = "AMR hits"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/ncbi-amrfinderplus:4.0.3--hf69ffd2_1"

[tool.hardware]
cpu_cores = 4
ram_gb = 8.0
disk_gb = 10.0

[tool.entrypoint]
command = "amrfinder"

[tool.binaries]
exposed = [ "amrfinder", "amrfinder_update",]

[tool.factored]
spec_path = "specs/amrfinderplus/4.0.3.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/amrfinderplus:4.0.3"
image_digest = "sha256:857d917aeba66fef023e2d77d8037ea2a83af101aa4115a2379d78d9b3914eef"

