[tool]
id = "whatshap"
version = "2.3"
description = "Read-based phasing of variants for short, long, and Hi-C reads"
homepage = "https://whatshap.readthedocs.io/"
license = "MIT"
tier = "core"
maintainers = [ "github:whatshap",]
[[tool.inputs]]
name = "vcf"
type = "vcf"
cardinality = "one"
description = "Unphased variants"

[[tool.inputs]]
name = "bam"
type = "bam"
cardinality = "one"
description = "Aligned reads"

[[tool.outputs]]
name = "phased"
type = "vcf"
cardinality = "one"
description = "Phased VCF"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/whatshap:2.3--py39h2de1943_3"

[tool.hardware]
cpu_cores = 4
ram_gb = 16.0
disk_gb = 10.0

[tool.entrypoint]
command = "whatshap"

[tool.binaries]
exposed = [ "whatshap",]

[tool.factored]
spec_path = "specs/whatshap/2.3.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/whatshap:2.3"
image_digest = "sha256:faffbad99d965900011279c5af4e43efb72c0ef8d0f68a07043f4210589cf276"
