name = "blast"
version = "2.14.0"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["blast ==2.14.0"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/blastn"
