[tool]
id = "bismark"
version = "0.24.2"
description = "Bisulfite read aligner and methylation caller"
homepage = "https://github.com/FelixKrueger/Bismark"
license = "GPL-3.0"
tier = "core"
maintainers = [ "github:FelixKrueger",]
[[tool.inputs]]
name = "reads"
type = "fastq"
cardinality = "many"
description = "Bisulfite-treated reads"

[[tool.inputs]]
name = "genome"
type = "dir"
cardinality = "one"
description = "Bismark-prepared reference dir"

[[tool.outputs]]
name = "bam"
type = "bam"
cardinality = "one"
description = "Methylation alignment"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/bismark:0.24.2--hdfd78af_0"

[tool.hardware]
cpu_cores = 8
ram_gb = 32.0
disk_gb = 50.0

[tool.entrypoint]
command = "bismark"

[tool.binaries]
exposed = [ "bismark", "bismark_genome_preparation", "bismark_methylation_extractor", "deduplicate_bismark",]

[tool.factored]
spec_path = "specs/bismark/0.24.2.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/bismark:0.24.2"
image_digest = "sha256:3378ab8ed841236bdc76c79e90c5d8e48db655d11b0cf93d6cc99e789fcfbb93"
