[tool]
id = "bakta"
version = "1.10.4"
description = "Rapid bacterial genome annotation with curated databases (modern prokka)"
homepage = "https://github.com/oschwengers/bakta"
license = "GPL-3.0"
tier = "core"
maintainers = [ "github:oschwengers",]
cache_paths = [ "/cache/bakta",]
[[tool.inputs]]
name = "genome"
type = "fasta"
cardinality = "one"
description = "Bacterial assembly"

[[tool.outputs]]
name = "outdir"
type = "dir"
cardinality = "one"
description = "Annotation outputs (GFF, GBK, FAA)"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/bakta:1.10.4--pyhdfd78af_1"

[tool.hardware]
cpu_cores = 8
ram_gb = 16.0
disk_gb = 30.0

[tool.entrypoint]
command = "bakta"

[tool.binaries]
exposed = [ "bakta", "bakta_db",]

[tool.factored]
spec_path = "specs/bakta/1.10.4.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/bakta:1.10.4"
image_digest = "sha256:7f5a66ffbb12a5f361d1778b36efe60c9c90fd1b3d43737953518d3be9caba2f"
